---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  labels:
    app: backend
  name: frontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: frontend
        image: nginx
        volumeMounts:
        - name: disk
          mountPath: /static
      - name: backend
        image: redis
        volumeMounts:
        - name: disk
          mountPath: /data/static
      restartPolicy: Always
      volumes:
      - name: disk
        emptyDir: {}
