---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  labels:
    app: backend
  name: frontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: frontend
          image: nginx
          volumeMounts:
          - name: my-volume
            mountPath: /static
        - name: backend
          image: redis
          volumeMounts:
          - name: my-volume
            mountPath: /data/static
      restartPolicy: Always
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: myPVC
