---
apiVersion: v1
kind: Pod
metadata:
  name: netology
  labels:
    app: netology
spec:
  containers:
  - name: frontend
    env:
    - name: BASE_URL
      value: "http://localhost:9000"
    image: perovss/frontend
    ports:
    - containerPort: 80
      protocol: TCP
  - name: backend
    image: perovss/backend
    env:
    - name: DATABASE_URL
      value: "postgres://postgres:postgres@db:5432/news"
    ports:
    - containerPort: 9000
      protocol: TCP
  - image: postgres:13-alpine 
    name: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_DB
      value: "news"
    ports:
    - containerPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netology
  name: frontend
spec:
  selector:
    app: netology
  ports:
  - name: frontend
    port: 8000
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netology
  name: backend
spec:
  selector:
    app: netology
  ports:
  - name: backend
    port: 9000
    protocol: TCP
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netology
  name: db
spec:
  selector:
    app: netology
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - host: help.example
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 8000
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 9000