---
apiVersion: v1
kind: Pod
metadata:
  name: netology
  labels:
    app: netology
spec:
  containers:
  - name: frontend
    image: perovss/frontend
  - name: backend
    image: perovss/backend
    env:
  - image: postgres:13-alpine 
    name: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_DB
      value: "news"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netology
  name: db
spec:
  selector:
    app: netology
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: 5432
