---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: perovss/backend
          name: backend
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@db:5432/news
          ports:
            - containerPort: 9000
      restartPolicy: Always
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'sleep 15']

