---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: frontend
  name: frontend
  namespace: product
spec:
  ports:
    - name: frontend
      port: 8000
      targetPort: 80
  selector:
    app: frontend
  type: ClusterIP