---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: db
  name: db
  namespace: product
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP