---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: product
spec:
  ports:
    - name: backend
      port: 9000
      targetPort: 9000
  selector:
    app: backend
  type: ClusterIP