---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: product
spec:
  serviceName: postges
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:13-alpine
        name: db
        env:
        - name: POSTGRES_DB
          value: news
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres