---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  labels:
    app: backend
  name: frontend-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: perovss/frontend
        name: frontend
        ports:
        - containerPort: 80
      - image: perovss/backend
        name: backend
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@db:5432/news
        ports:
        - containerPort: 9000
      restartPolicy: Always
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'sleep 15']