---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fb
  name: frontend
  namespace: stage
spec:
  ports:
  - name: frontend
    port: 8000
    targetPort: 80
  selector:
    app: fb
  type: ClusterIP