---
apiVersion: v1
kind: Service
metadata:
  namespace: stage
  annotations:
  labels:
    app: db
  name: db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP